import type { Metadata } from "next";
import "./globals.css";
import stylex from "@stylexjs/stylex";
import { weightFont, colors, fontFamily } from "../tokens.stylex";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const MAXWIDTH = "@media screen and (max-width: 600px)";

const styles = stylex.create({
  font: {
    fontFamily: fontFamily.Epilogue,
    fontSize: 16,
    color: colors["cinza-600"],
    WebkitFontSmoothing: "antialiased",
    MozOsxFontSmoothing: "grayscale",
  },
  body: {
    fontFamily: fontFamily.Epilogue,
    fontSize: 16,
  },
  "*": {
    padding: 0,
    margin: 0,
    boxSizing: "border-box",
    fontFamily: fontFamily.Epilogue,
  },
  code: {
    fontFamily: fontFamily.Epilogue,
  },
  button: {
    fontFamily: fontFamily.Epilogue,
  },
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        {...stylex.props(
          styles.font,
          styles["*"],
          styles.button,
          styles.code,
          styles.body
        )}
      >
        {children}
      </body>
    </html>
  );
}
